api_platform:
    collection:
        pagination:
            client_items_per_page: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
framework:
    form: { enabled: true }
